import mongoose from 'mongoose';

const settingsSchema = new mongoose.Schema({
  general: {
    systemName: { type: String, default: 'RVNP Campus Hub' },
    tagline: { type: String, default: 'The Digital Quad of Rift Valley National Polytechnic' },
    supportEmail: { type: String, default: 'support@hdm.com' },
    supportPhone: { type: String, default: '' },
    language: { type: String, default: 'en' },
    timezone: { type: String, default: 'Africa/Nairobi' },
    dateFormat: { type: String, default: 'DD/MM/YYYY' },
    logo: { type: String, default: '' },
    favicon: { type: String, default: '' },
    maintenanceMessage: { type: String, default: 'Under maintenance. We will be back shortly.' },
  },
ai: {
  aiEnabled: { type: Boolean, default: true },
  chatEnabled: { type: Boolean, default: true },
  moderationEnabled: { type: Boolean, default: true },
  moderationSensitivity: { type: Number, default: 0.75, min: 0, max: 1 },
  autoFlagThreshold: { type: Number, default: 0.3, min: 0, max: 1 },
  verificationScanEnabled: { type: Boolean, default: true },
  smartFeedEnabled: { type: Boolean, default: true },
  suggestedRepliesEnabled: { type: Boolean, default: true },
  trendingEnabled: { type: Boolean, default: true },
  modelVersion: { type: String, default: 'v2.1' },
},
  email: {
    senderName: { type: String, default: 'RVNP Campus Hub' },
    senderEmail: { type: String, default: '' },
    templates: { type: mongoose.Schema.Types.Mixed, default: {} },
  },
  sms: {
    senderId: { type: String, default: 'HDM' },
    templates: { type: mongoose.Schema.Types.Mixed, default: {} },
    timeRestrictionEnabled: { type: Boolean, default: true },
  },
  legals: {
    termsOfService: { type: String, default: '' },
    privacyPolicy: { type: String, default: '' },
    communityGuidelines: { type: String, default: '' },
    marketplacePolicy: { type: String, default: '' },
    lastUpdated: { type: Date, default: Date.now },
    requireReaccept: { type: Boolean, default: false },
  },
  uploads: {
    maxFileSizeMB: { type: Number, default: 20 },
    allowedTypes: [{ type: String }],
    maxPostImages: { type: Number, default: 5 },
    maxMarketImages: { type: Number, default: 4 },
    maxAvatarSizeMB: { type: Number, default: 2 },
    maxStorySizeMB: { type: Number, default: 15 },
    maxChatFileSizeMB: { type: Number, default: 25 },
  },
toggles: {
  userRegistration: { type: Boolean, default: true },
  posts: { type: Boolean, default: true },
  stories: { type: Boolean, default: true },
  chat: { type: Boolean, default: true },
  groups: { type: Boolean, default: true },
  marketplace: { type: Boolean, default: true },
  verification: { type: Boolean, default: true },
  leaderboard: { type: Boolean, default: true },
  live: { type: Boolean, default: true },
  maintenanceMode: { type: Boolean, default: false },
  betaFeatures: { type: Boolean, default: false },
},
  downloads: {
    playStoreUrl: { type: String, default: '' },
    appStoreUrl: { type: String, default: '' },
    apkUrl: { type: String, default: '' },
    downloadPageEnabled: { type: Boolean, default: false },
    minAppVersion: { type: String, default: '1.0.0' },
    updateMessage: { type: String, default: 'A new version is available.' },
  },
  backups: {
    schedule: { type: String, enum: ['daily', 'weekly', 'manual'], default: 'daily' },
    time: { type: String, default: '03:00' },
    retentionCount: { type: Number, default: 7 },
    storageLocation: { type: String, default: '' },
    lastBackupDate: { type: Date, default: null },
    lastBackupStatus: { type: String, default: null },
  },
  pricing: {
    verificationFeeKsh: { type: Number, default: 200 },
    renewalEnabled: { type: Boolean, default: false },
    discountCodes: [{ code: String, percentage: Number, expiresAt: Date }],
  },
  badges: {
    topContributorWeeklyCount: { type: Number, default: 10 },
    topContributorMonthlyCount: { type: Number, default: 20 },
    topFanThreshold: { type: Number, default: 30 },
    marketplaceChampionSales: { type: Number, default: 10 },
    marketplaceChampionRating: { type: Number, default: 4.5 },
    storyStarDays: { type: Number, default: 7 },
    groupBuilderMembers: { type: Number, default: 50 },
    lostFoundHeroReturns: { type: Number, default: 3 },
    qaExpertAnswers: { type: Number, default: 10 },
    earlyAdopterThreshold: { type: Number, default: 1000 },
  },
  scoring: {
    post: { type: Number, default: 3 },
    comment: { type: Number, default: 1 },
    helpfulAnswer: { type: Number, default: 5 },
    listingSold: { type: Number, default: 4 },
    lostFoundReturned: { type: Number, default: 10 },
    groupFileUpload: { type: Number, default: 2 },
    storyPosted: { type: Number, default: 1 },
    repost: { type: Number, default: 2 },
  },
  limits: {
    postMaxChars: { type: Number, default: 2000 },
    commentMaxChars: { type: Number, default: 500 },
    listingTitleMaxChars: { type: Number, default: 100 },
    listingDescriptionMaxChars: { type: Number, default: 1000 },
    groupNameMaxChars: { type: Number, default: 50 },
    groupDescriptionMaxChars: { type: Number, default: 500 },
    chatMessageMaxChars: { type: Number, default: 2000 },
    storyCaptionMaxChars: { type: Number, default: 200 },
    postsPerPage: { type: Number, default: 20 },
    chatsPerPage: { type: Number, default: 30 },
    marketPerPage: { type: Number, default: 20 },
    usersPerPage: { type: Number, default: 50 },
    notificationsPerPage: { type: Number, default: 30 },
  },
  jobs: {
    weeklyAwards: { type: String, default: '0 8 * * 1' },
    monthlyAwards: { type: String, default: '0 8 1 * *' },
    storyCleanup: { type: String, default: '0 * * * *' },
    feedRanking: { type: String, default: '*/30 * * * *' },
  },
}, { timestamps: true });

export default mongoose.model('Settings', settingsSchema);